name: Release

on:
  push:
    tags:
      - "v*"
      - "test-v*"
  pull_request:

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builder:
    strategy:
      max-parallel: 2
      fail-fast: true
      matrix:
        arch: [x86_64, aarch64]
        include:
          - arch: x86_64
            os: ubuntu-latest
          - arch: aarch64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    name: builder-${{ matrix.arch }}
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Build
        run: make save-builder

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: builder-${{ matrix.arch }}
          path: builder-${{ matrix.arch }}.tar
          overwrite: true

  image:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        arch: [x86_64, aarch64]
        runtime: [none, docker, containerd, incus]
        dist: [ubuntu, debian]
        include:
          - arch: x86_64
            os: ubuntu-latest
          - arch: aarch64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    needs: [builder]
    name: img-${{ matrix.arch }}-${{ matrix.dist }}-${{ matrix.runtime }}
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: builder-${{ matrix.arch }}

      - name: Build
        run: |
          docker load -i builder-${{ matrix.arch }}.tar
          make DIST=${{ matrix.dist }} ${{ matrix.runtime }}
          ls -lah dist/img

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: img-${{ matrix.arch }}-${{ matrix.dist}}-${{ matrix.runtime }}
          path: dist/img/${{ matrix.dist}}-*-${{ matrix.runtime }}.*
          overwrite: true
          retention-days: 1
          compression-level: 0

  release:
    runs-on: ubuntu-latest
    needs: [image]
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
      actions: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 1
          persist-credentials: false

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist/img

      - name: Create
        run: >
          tag="${GITHUB_REF##*/}"

          gh release create "${tag}" --draft --title "${tag}" dist/img/*/*.raw.gz dist/img/*/*.sha512sum

      - name: Delete build artifacts
        if: always()
        run: |
          gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
            --jq '.artifacts[].id' | xargs -r -I {} gh api -X DELETE repos/${{ github.repository }}/actions/artifacts/{}

