name: Renovate

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 1
          persist-credentials: false

      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: renovate

      - uses: renovatebot/github-action@v46.1.16
        with:
          configurationFile: .github/renovate.json
        env:
          RENOVATE_TOKEN: ${{ steps.octo-sts.outputs.token }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
